server:
  port: 8023
  forward-headers-strategy: native

logging:
  level:
    root: info
    com.myce: debug

internal:
  auth:
    value: internal-request

spring:
  application:
    name: payment-internal
  profiles:
    active: ${PROFILE:local}
    include:
      - domain
      - common

  config:
    import:
      - optional:aws-parameterstore:/myce/common/
      - optional:aws-parameterstore:/myce/${spring.profiles.active}/

  # 포트원 설정

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    persistAuthorization: true
  api-docs:
    path: /v3/api-docs

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    prefer-ip-address: true
    ip-address: ${PAYMENT_INTERNAL_URL}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  prometheus:
    metrics:
      export:
        enabled: true

port-one:
  base-url: ${PORTONE_BASE_URL}
  api-key: ${PORTONE_API_KEY}
  api-secret: ${PORTONE_API_SECRET}
  customer-code: ${PORTONE_CUSTOMER_CODE}
